<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To date</name>
   <tag></tag>
   <elementGuidId>509f56f1-fea9-4441-8c42-b30898b32c91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#q_updated_at_lteq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='q_updated_at_lteq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bee235d0-4f4d-4043-9256-31adfc775b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6f10abcd-dd9b-4f19-b986-8b5b975290e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>58001ab2-cda9-4fb5-99b0-b7ef9b48ba22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q[updated_at_lteq]</value>
      <webElementGuid>761a9217-39ce-48cf-966d-220358d867cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>q_updated_at_lteq</value>
      <webElementGuid>c81e22d9-25ce-43c9-b81a-f34e613bb7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q_updated_at_lteq&quot;)</value>
      <webElementGuid>d5e82ffb-b076-4d1e-a06d-024b7fc9decc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='q_updated_at_lteq']</value>
      <webElementGuid>46d440ea-13d1-4ccf-b92b-80728a47193a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-size']/div/div[2]/input</value>
      <webElementGuid>b0b9270a-4951-45c8-b58f-9548337980e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>11347240-26a8-4844-9050-ae7bab22deb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'q[updated_at_lteq]' and @id = 'q_updated_at_lteq']</value>
      <webElementGuid>e2684c56-f005-46e2-8f33-696c4023d7ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
