<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report_search</name>
   <tag></tag>
   <elementGuidId>c600700f-a075-4b11-81d7-c80e138c9012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#q_text_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='q_text_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f954e617-31e9-4776-a9ff-004db628c31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>28009442-cac9-43fe-beba-0327036ae5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>64fe8f9e-4a02-4b92-948d-f827597a0501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>eb4eb91b-403a-4192-aa6e-e9a6dde24d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q[text_search]</value>
      <webElementGuid>8da09b2a-187a-42d8-af32-b29a254c5806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>q_text_search</value>
      <webElementGuid>c4aadc7c-cc61-40b2-9cef-8ee660f5185e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q_text_search&quot;)</value>
      <webElementGuid>6f144e32-a746-451a-91bd-b4a0c86c2993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='q_text_search']</value>
      <webElementGuid>2d69dd72-a263-4d50-b9ea-bea632e41c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReport']/div/div/input</value>
      <webElementGuid>5918b5ee-7755-446c-a225-30c81490234b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>3f9960a3-d70e-4f43-bc4c-7a1a77028f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @type = 'search' and @name = 'q[text_search]' and @id = 'q_text_search']</value>
      <webElementGuid>b95b7896-c3e5-46a5-9aa8-310b51c920c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
