<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From date</name>
   <tag></tag>
   <elementGuidId>1997eebf-3df1-41ba-8a62-02587045c4b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#q_updated_at_gteq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='q_updated_at_gteq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68d6bec4-c8d1-436d-b4ae-1150a6a8ddb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f1675e94-d311-46cb-bc10-7e95e8f69483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>a5f85fe4-2cd8-485e-8e66-82c073a8e8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q[updated_at_gteq]</value>
      <webElementGuid>70611223-7067-4cde-a325-0485c6814cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>q_updated_at_gteq</value>
      <webElementGuid>2ecd3693-c68b-4c47-ac2f-ae3602cacd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q_updated_at_gteq&quot;)</value>
      <webElementGuid>797bca4a-e6e7-4df2-a0fc-5dc112919537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='q_updated_at_gteq']</value>
      <webElementGuid>5d1bc6f9-c7cf-4ade-adad-8c9021236d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-size']/div/div/input</value>
      <webElementGuid>366cd9d8-ef0c-4d8a-b0c9-e8fa11983323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>5c30fb36-614e-49b4-bd56-1445ce7c4f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'q[updated_at_gteq]' and @id = 'q_updated_at_gteq']</value>
      <webElementGuid>bc0878c0-9679-4e60-90b6-fe17d24180bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
