<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Q.C</name>
   <tag></tag>
   <elementGuidId>4113b755-7b78-4f40-88a3-835300039f4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mx-5.d-flex.align-items-center.justify-content-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/div[2]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>741c047a-1ad7-43e0-8292-1c0507da0ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-5 d-flex align-items-center justify-content-center</value>
      <webElementGuid>ca57dde9-e307-40e8-ba1d-51232166e497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pols/qc</value>
      <webElementGuid>be92f49b-99b5-403e-86b8-248344f81ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Q.C.</value>
      <webElementGuid>a79ccfea-a6b5-4706-a948-1afb7a1bd6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;info&quot;]/div[@class=&quot;boder-blue&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;menu-tab d-flex mb-5 mt-5&quot;]/a[@class=&quot;mx-5 d-flex align-items-center justify-content-center&quot;]</value>
      <webElementGuid>2fb65dcb-8a89-4b4e-816d-8d28dbd5a2a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[2]/div/a[2]</value>
      <webElementGuid>39266d54-7411-447c-a03d-e2fb34d1c300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Q.C.')]</value>
      <webElementGuid>a8cd1155-de2a-4ded-b8e9-79ce25810d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive Item'])[1]/following::a[1]</value>
      <webElementGuid>45a7c206-b427-4be0-8dd6-cf4955dcd2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive &amp; Q.C.'])[1]/following::a[2]</value>
      <webElementGuid>43af2728-2b18-450c-a26d-f5cb440431fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packing'])[1]/preceding::a[1]</value>
      <webElementGuid>3eae9448-96cc-48fa-a900-400373757a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/preceding::a[2]</value>
      <webElementGuid>1304bdda-3b08-44b6-bed1-139e92c2a6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Q.C.']/parent::*</value>
      <webElementGuid>7c5b3564-02ed-4903-82ba-a040b4a866e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pols/qc')]</value>
      <webElementGuid>00657dab-fe7f-4900-b839-e7839991f3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>5b2ccc51-1cfa-42b0-af72-451f8a781e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pols/qc' and (text() = 'Q.C.' or . = 'Q.C.')]</value>
      <webElementGuid>ddb42421-751b-497f-a15a-4159aa48fe13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
