<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO-C_search</name>
   <tag></tag>
   <elementGuidId>17abe979-90ef-4cfc-b858-f4f6c949df54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#q_text_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='q_text_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7dc7f16-0af9-4d94-a7e8-8604856fb344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>29d06917-8e98-4c85-b2ad-74bec87b867d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>3f987e2a-8c50-4bc6-9424-ae60dc27c909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6fce7f39-e50a-414f-a84d-4a94e032eef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12064</value>
      <webElementGuid>67c69811-bdcc-4a6d-97b4-dd5e8d693679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q[text_search]</value>
      <webElementGuid>08f8b245-778c-4b71-8a6f-921b75618d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>q_text_search</value>
      <webElementGuid>675c8396-d3a5-4444-a325-e36b8606f2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q_text_search&quot;)</value>
      <webElementGuid>ede6bc7b-6063-45e1-b06b-879e41a2ce96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='q_text_search']</value>
      <webElementGuid>41ea5793-3dc1-4430-b92d-bb22f353a63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='poc_search']/div/div/input</value>
      <webElementGuid>1d0b4b40-4c80-4694-b1a3-c5ab3863e8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>126ac06a-0093-42da-babd-4c0f1d821dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @type = 'search' and @name = 'q[text_search]' and @id = 'q_text_search']</value>
      <webElementGuid>a6fef4d2-f814-443e-b30e-6b60a72112ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
