<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Inhouse_item</name>
   <tag></tag>
   <elementGuidId>08285cc5-9e69-4a67-862a-2d1d3df55795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itsInhouseBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#itsInhouseBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5eb4ce4-cf25-4755-8f7f-11dcef24f359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-box-size3 mx-2</value>
      <webElementGuid>a4d88f5b-2627-4489-afaf-551be80030f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itsInhouseBtn</value>
      <webElementGuid>da7bc02f-c770-4ac6-9945-98fa6543b0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>click->check-btn#toggleDisplayAddBtn click->check-btn#checkInhouseMaterials</value>
      <webElementGuid>6a69bce3-bfb2-4401-a078-a78a3bb9eb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a07ce96a-ee1a-4d36-a9ab-adf7beaa09de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ec0265bd-b494-43bf-802f-34c08523720a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[in_house]</value>
      <webElementGuid>42e8ef7d-1dee-4155-b43f-a9635fbe0363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itsInhouseBtn&quot;)</value>
      <webElementGuid>b68053bc-71d3-40fb-8951-44b806b55d38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itsInhouseBtn']</value>
      <webElementGuid>86b7236b-b31b-48d5-811a-43deb8ba619b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[2]/div/div[4]/div/input[2]</value>
      <webElementGuid>d494db25-1243-4915-9975-077149afed4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>336de466-86ef-46ef-9d5b-5d0743f7a5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'itsInhouseBtn' and @type = 'checkbox' and @name = 'product[in_house]']</value>
      <webElementGuid>1a1d1cb4-8217-408d-88aa-6353fc51fc79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
