<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Cost_productknitting_cost</name>
   <tag></tag>
   <elementGuidId>ecb61dd6-a142-4e96-afa1-969e10be0071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_knitting_cost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_knitting_cost</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7062aefb-8684-49fc-bf7d-bd540c034766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control_input--custom is-invalid</value>
      <webElementGuid>25b6aa9a-9c7c-408c-abcf-2f8f3b742441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>58aa2ecd-fadf-432d-a1c7-d56eb669b68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>309bdbe9-90f2-4100-9173-573eadc318cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>d4f8b543-6e6d-444b-aed6-6637eeda65e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fda74a78-e21b-4515-af81-78a7d0792d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[knitting_cost]</value>
      <webElementGuid>05069612-0f3d-4340-8a01-182eb726948d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_knitting_cost</value>
      <webElementGuid>3b02c9b1-d2ff-4b94-9c77-563029eabedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_knitting_cost&quot;)</value>
      <webElementGuid>8a78ebb5-7a03-4231-909c-f8266026a37d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_knitting_cost']</value>
      <webElementGuid>5303cc09-ce41-44c5-9f22-c03d2e4608af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div[4]/div/div/div[2]/div/div[8]/div/input</value>
      <webElementGuid>c0e0992d-c105-4bfa-91ff-8f31bb4a1a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>c1f41f41-082d-4690-af1e-e0058c95af87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product[knitting_cost]' and @id = 'product_knitting_cost']</value>
      <webElementGuid>8ce39b83-5ed0-4797-9ebe-480275550de5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
