<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ironing</name>
   <tag></tag>
   <elementGuidId>23b185e4-5aa0-41ff-a179-5064bc6dbc7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_ironing_cost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_ironing_cost</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'number' and @name = 'product[ironing_cost]' and @id = 'product_ironing_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f51c8dd3-f93f-4b66-8b4d-1f2db2ab07a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control_input--custom</value>
      <webElementGuid>b0de8867-e8ca-4941-a9c2-68a570cbff57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16f10e5c-8584-40ab-914e-9c40796f7aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>5d553695-ee15-4b66-b9a8-28bc8711b479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>42436bec-832c-407f-ba56-cb000b9b6ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>586b6822-a686-4cf4-969d-17c7e33aaf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[ironing_cost]</value>
      <webElementGuid>dfda0795-e593-4f21-a6d7-b706ec3218e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_ironing_cost</value>
      <webElementGuid>c4792c4e-c274-4a51-898d-c6224d2e2f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_ironing_cost&quot;)</value>
      <webElementGuid>a26ce900-51f4-437b-931d-6d1f4927b108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_ironing_cost']</value>
      <webElementGuid>20856c1e-d48c-4ee1-956c-86075b15b1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div[4]/div/div/div[2]/div/div[11]/input</value>
      <webElementGuid>70c35762-5963-4bd4-bb35-8100da1ae366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>adcb0d8e-7935-4b24-9bb1-c5ccfe1f568a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product[ironing_cost]' and @id = 'product_ironing_cost']</value>
      <webElementGuid>369ce305-6712-4547-a702-32d41ab7e73a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
