<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StyleVendor_productstyle_vendor</name>
   <tag></tag>
   <elementGuidId>f6c57011-05c9-437a-87cc-2221f54ea26b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_style_vendor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_style_vendor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a2c4ef3-6cf5-48bc-8f8e-24902573e6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9014d162-6124-4ffe-b368-1c7d060129ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36e87694-4162-4f9d-b0b0-7fb612eaae0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[style_vendor]</value>
      <webElementGuid>69f0757f-c44a-4ffe-a511-9f83574c60e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_style_vendor</value>
      <webElementGuid>56acf171-c929-4515-8658-c26100177b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_style_vendor&quot;)</value>
      <webElementGuid>b20fd86b-7aa2-4c35-ac78-14b1ef5164c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_style_vendor']</value>
      <webElementGuid>fd738a9f-1d37-4155-9d1f-7690864d336b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>0d1099f2-8312-4c2b-bd76-0f6f15e21891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>62250142-a54a-430a-9851-820cf600a958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'product[style_vendor]' and @id = 'product_style_vendor']</value>
      <webElementGuid>d3c689ef-b099-47ca-a2b4-be1c6d7b04e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
