<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_labeling_bagging_cost</name>
   <tag></tag>
   <elementGuidId>d73d3f14-3464-4f75-ab5a-1a17adb65387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_labeling_bagging_cost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_labeling_bagging_cost</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e300703d-102b-426e-85d2-238181c5dae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control_input--custom</value>
      <webElementGuid>73f5b92b-ebd3-43bc-a59b-e441c51f5980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78f1ff1e-f137-4aae-ad3f-03b7dfda4124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>056f9e50-f6eb-427e-bb58-c30d2b0d5ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>daa3f8ab-57c2-41f1-8dd3-4999a2deb974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2dae0692-cd80-4d6d-bbb7-53acfc4243c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[labeling_bagging_cost]</value>
      <webElementGuid>2816b4c4-6e7b-4e2a-8169-659f98d37be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_labeling_bagging_cost</value>
      <webElementGuid>d15e5775-b19f-41df-9f63-d1091c3462fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_labeling_bagging_cost&quot;)</value>
      <webElementGuid>ba7780a5-c790-4b7a-8ce3-e9969b41fcfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_labeling_bagging_cost']</value>
      <webElementGuid>eaf27f9b-a4ca-420c-bf4f-31b578cb4a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div[4]/div/div/div[2]/div/div[12]/input</value>
      <webElementGuid>737c5d86-4f50-49fc-b669-da97acb50826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>f8df532b-7010-4cf8-9ea7-b4be53c001dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product[labeling_bagging_cost]' and @id = 'product_labeling_bagging_cost']</value>
      <webElementGuid>bbb3796c-fc74-4745-85e8-d6aa27f9b054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
