<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Descrtiption Thai_productdescrip_th</name>
   <tag></tag>
   <elementGuidId>bd801ac8-6d93-43c8-abd0-073efa0a0f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='product_descrip_th']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_descrip_th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b942502c-6928-4f14-bd67-4f5864c1490b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f0f3f756-b1bf-4d97-ad9e-405646cfccf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[descrip_th]</value>
      <webElementGuid>e3c34041-e62f-4658-9aea-8a40e9066f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_descrip_th</value>
      <webElementGuid>6f65675a-6b7b-4a44-8b1f-3aa0d62ff4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_descrip_th&quot;)</value>
      <webElementGuid>36aa79c5-7862-48a3-91e7-b92a9dba51e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='product_descrip_th']</value>
      <webElementGuid>b821c8eb-8f34-4699-82ed-6a22e3a995ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[2]/div[3]/textarea</value>
      <webElementGuid>0e120a10-eb52-4a13-90c1-e03ab58f31d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>20cd1543-3795-44e6-92aa-e4e4c3c42d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'product[descrip_th]' and @id = 'product_descrip_th']</value>
      <webElementGuid>c542217e-6c0b-4f53-b246-413f2f3e21a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
