<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Color Description Thai_productcolor_descrip</name>
   <tag></tag>
   <elementGuidId>5f27e86b-f8aa-46b9-8cbb-724420083ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='product_color_descrip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_color_descrip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>20cf8831-2be1-4ce5-b10a-e51d4cddbb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c8a375ca-2bbe-4ce4-a96a-fd797dab41ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[color_descrip]</value>
      <webElementGuid>7fc09ed2-f844-430a-9663-cb983663fa0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_color_descrip</value>
      <webElementGuid>3542e5d8-25df-42f8-91ae-982cc4eab500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_color_descrip&quot;)</value>
      <webElementGuid>0c7d5271-3972-4192-bf60-d1bfd34b589a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='product_color_descrip']</value>
      <webElementGuid>da7302c4-0524-4b38-a6df-f5879ef821cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[2]/div[4]/div[2]/textarea</value>
      <webElementGuid>c4a787dc-f6e6-4156-a8f5-362c8152a86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/textarea</value>
      <webElementGuid>d6775906-6c8a-4ee1-9d1d-c3dc957cc466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'product[color_descrip]' and @id = 'product_color_descrip']</value>
      <webElementGuid>bf52d3e9-62d7-4c35-801d-2a54308cb066</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
