<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Scan barcode_input-receive</name>
   <tag></tag>
   <elementGuidId>95f1e995-2e3b-496d-a3a6-949d4c965eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-packing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-packing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c160eca-850a-4eb0-98f4-44272d7163d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control barcode mb-3 me-3</value>
      <webElementGuid>b9896522-f5c9-4727-8acc-bc74aaafea83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-packing</value>
      <webElementGuid>3b9e05f2-55ae-4be3-9eee-c5ed21bb83bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>b6e536e2-1a95-4992-b63f-ba716db21f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>keyup->packing#scanBarcode</value>
      <webElementGuid>36316ec5-979c-42d6-8092-d777555e1f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fcac0c5-36da-45a7-afe7-80617887e9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-receive</value>
      <webElementGuid>7b49d93d-4fcb-4d3d-91d4-502e26883ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-packing&quot;)</value>
      <webElementGuid>7f4fc078-6447-47a1-8e85-c7eefdc35d18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-packing']</value>
      <webElementGuid>8cc3562f-6bb2-4ff6-bf9a-407b9444a3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/input</value>
      <webElementGuid>40b3ef1f-966a-4318-ae7b-ac3dccf9750a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0cbba7ab-4bb8-461e-a99b-3d2c505258a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-packing' and @placeholder = 'Barcode' and @type = 'text' and @name = 'input-receive']</value>
      <webElementGuid>16ab427a-5e0f-41a6-9c42-80f38bd0b8f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
