<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Barcode</name>
   <tag></tag>
   <elementGuidId>e3a3f6b9-0128-45e0-965e-3952dfcfce4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='packingTable']/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>626c67b3-ba1e-4a66-95b7-ea50d9331b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>e1e097b4-3dc3-4c58-827d-80088be067d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;packingTable&quot;)/thead[@class=&quot;thead-light select-boder-none&quot;]/tr[1]/th[1]</value>
      <webElementGuid>e54010e0-cca2-4b00-8aa0-4d1dd28de12b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='packingTable']/thead/tr/th</value>
      <webElementGuid>9a69b0a6-2f51-4116-90e9-a622ecc3ce1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan barcode'])[1]/following::th[1]</value>
      <webElementGuid>2e971712-a30c-4c23-a171-5ddf145554e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/following::th[1]</value>
      <webElementGuid>b9e851f6-7b62-470a-bbec-4ae30f9046b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leader'])[1]/preceding::th[1]</value>
      <webElementGuid>e37ad6bf-60b7-4f1d-9b2c-d87a3f9b863d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO-L'])[1]/preceding::th[2]</value>
      <webElementGuid>0000192e-2bf8-4a05-b40e-5a1edf015c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Barcode']/parent::*</value>
      <webElementGuid>216f919c-5505-4525-8b89-d7fa0987fe12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>994a65f9-9422-4f81-992f-d24bada2d2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Barcode' or . = 'Barcode')]</value>
      <webElementGuid>a5aaaf55-9126-4cdf-9ac6-a74d23bafd7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
