<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Inhouse</name>
   <tag></tag>
   <elementGuidId>a74c3cf1-a961-4fdd-a530-4293dca7469e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Inhouse')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d9f64117-4f4f-4221-bd36-cc9c74ae50ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sort_link  head-table</value>
      <webElementGuid>c711cbf3-bce0-404c-baa0-95ed4577dcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products?q%5Bs%5D=in_house+desc</value>
      <webElementGuid>728e6d0d-6eb0-499e-9c3b-55d636d1d249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inhouse</value>
      <webElementGuid>206a6248-bb30-4c05-b566-879f33b761d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;h-100&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main_content&quot;]/div[@class=&quot;info&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 table-custom&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table align-middle&quot;]/thead[@class=&quot;select-boder-none&quot;]/tr[1]/th[@class=&quot;col-sm-1&quot;]/a[@class=&quot;sort_link  head-table&quot;]</value>
      <webElementGuid>15e86a9d-0776-48cb-a581-7124b72660f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Inhouse')]</value>
      <webElementGuid>b0ed7d05-9402-44fc-8dd0-013903bc0857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catagory'])[1]/following::a[1]</value>
      <webElementGuid>9e5c01d0-9f73-46a3-99a2-5e5bc12a8b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::a[2]</value>
      <webElementGuid>9ba73e9f-67d6-4cce-a6fc-b1696edd6a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated at'])[1]/preceding::a[2]</value>
      <webElementGuid>d02e974d-7e2c-44be-b4a9-807d8e99e376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inhouse']/parent::*</value>
      <webElementGuid>23997e3c-002b-406c-b228-943c3003cb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products?q%5Bs%5D=in_house+desc')]</value>
      <webElementGuid>e027efaf-b47f-4a18-b89a-fd5fe1054f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/a</value>
      <webElementGuid>4e7c823c-db42-4b7b-abc3-f364e1faf80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products?q%5Bs%5D=in_house+desc' and (text() = 'Inhouse' or . = 'Inhouse')]</value>
      <webElementGuid>38489f9b-24bf-4872-85e2-24a9de73f2b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
