<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>33f73f2d-f0fc-4008-8b3c-c325e87a2056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/form/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn-custom.btn--outline-primary.text-decoration-none.ms-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dceb640a-a66f-48a3-8756-71fe5936a546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-custom btn--outline-primary text-decoration-none ms-4</value>
      <webElementGuid>e64d83fe-871b-4073-a82c-0b9a38ba77e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products</value>
      <webElementGuid>d5540cdd-4278-4e22-af7a-79b93bcf95de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>0a349fe2-62b4-4098-bbe2-caebea6cb922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;info&quot;]/form[@class=&quot;form-custom nested_fields needs-validation&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;d-flex flex-row-reverse&quot;]/a[@class=&quot;btn-custom btn--outline-primary text-decoration-none ms-4&quot;]</value>
      <webElementGuid>6e119472-e6cc-4cbc-b020-e6d59c98f1de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div[2]/div/a</value>
      <webElementGuid>370c8f0c-d931-4dbf-a5cd-6c56e2bcd1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>6e34d6fc-e3d0-4ce7-8e2a-340b5ebb1df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill TH Price'])[1]/following::a[1]</value>
      <webElementGuid>28914404-f65c-482e-8df8-babb413c55b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill B2C in USD'])[1]/following::a[1]</value>
      <webElementGuid>d271469f-3025-4fbd-b975-6817be25df13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::a[1]</value>
      <webElementGuid>7e7cdd05-fc89-475e-b3fb-55e52f9a802d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure ?'])[2]/preceding::a[1]</value>
      <webElementGuid>5d67a66f-f672-4e63-9a9c-210d900f3ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products')])[4]</value>
      <webElementGuid>44dc3051-9ab5-4636-9a5f-d5aaabcd3e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/a</value>
      <webElementGuid>99dd4345-7c0e-462b-a598-ee2986e63a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>bd01c83d-4cea-46e1-a361-b9d999d58e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
