<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Comfirm Duplicate</name>
   <tag></tag>
   <elementGuidId>59991000-d8e5-4df8-b3ed-13a220a202c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn-custom.btn--primary.text-decoration-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='staticBackdrop']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>961713cb-65ab-45b6-bda0-15f73c1a95cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-custom btn--primary text-decoration-none</value>
      <webElementGuid>01d90472-f64f-4346-b5f3-96ee62e439e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/new?duplicate_id=1735</value>
      <webElementGuid>8ea11f74-286a-436b-91da-23ef954dcda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comfirm</value>
      <webElementGuid>17dff048-71b1-4edc-9fb0-df52d1685336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;staticBackdrop&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-custom&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;mt-5&quot;]/a[@class=&quot;btn-custom btn--primary text-decoration-none&quot;]</value>
      <webElementGuid>5429d663-2d4a-4b41-b608-9d214e402023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='staticBackdrop']/div/div/div/div/a</value>
      <webElementGuid>0a0e97ea-fce7-41d2-9f97-59bb7905f1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Comfirm')]</value>
      <webElementGuid>88c51197-876d-4ebd-b8de-32c5ca9e6bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::a[1]</value>
      <webElementGuid>3fca16ef-4fc2-42c2-babc-c58fe332c46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure ?'])[1]/following::a[1]</value>
      <webElementGuid>5058aa6b-e043-4b9f-9902-c2ef1120b094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product info.'])[1]/preceding::a[1]</value>
      <webElementGuid>7d9b9f8d-9051-49fa-8a63-685cbd8c7b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Picture'])[1]/preceding::a[1]</value>
      <webElementGuid>6866d904-914c-4ba4-849d-a5d1b7219106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comfirm']/parent::*</value>
      <webElementGuid>876e3f36-94f4-488b-9322-b5fe2645ba1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/new?duplicate_id=1735')]</value>
      <webElementGuid>5c664942-92ca-4925-8299-4d34772f4006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>e06cbb99-775f-47a0-9dfd-5a4d8942c32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/new?duplicate_id=1735' and (text() = 'Comfirm' or . = 'Comfirm')]</value>
      <webElementGuid>7dd543c3-eec2-4ba2-94fa-638b60312cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
